const ERROR_CODES = {
  // Auth
  AUTHENTICATION_FAILED: 'AUTHENTICATION_FAILED',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',

  // User
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  EMAIL_ALREADY_EXISTS: 'EMAIL_ALREADY_EXISTS',

  // Attendance
  ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',
  ALREADY_PUNCHED_IN: 'ALREADY_PUNCHED_IN',
  NOT_PUNCHED_IN: 'NOT_PUNCHED_IN',
  ALREADY_PUNCHED_OUT: 'ALREADY_PUNCHED_OUT',

  // Input & Geofence
  SELFIE_REQUIRED: 'SELFIE_REQUIRED',
  LOCATION_REQUIRED: 'LOCATION_REQUIRED',
  INVALID_LOCATION: 'INVALID_LOCATION',
  GEOFENCE_OUT_OF_RANGE: 'GEOFENCE_OUT_OF_RANGE',
  VALIDATION_ERROR: 'VALIDATION_ERROR',

  // Overtime
  OVERTIME_EXISTS: 'OVERTIME_EXISTS',
  OVERTIME_NOT_FOUND: 'OVERTIME_NOT_FOUND',
  OVERTIME_ALREADY_REVIEWED: 'OVERTIME_ALREADY_REVIEWED',
  OVERTIME_REQUIRES_PUNCHOUT: 'OVERTIME_REQUIRES_PUNCHOUT',

  // Server
  INTERNAL_ERROR: 'INTERNAL_ERROR',
};

module.exports = { ERROR_CODES };
